export const ADMIN_ROUTER = '/admin'
export const LOGIN_ROUTER = '/login'
export const REGISTRATION_ROUTER = '/registration'
export const SHOP_ROUTER = '/'
export const PRODUCT_ROUTER = '/product'
export const BASKET_ROUTE = '/basket'
export const CATALOG_ROUTE = '/catalog'